spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security
    username: root
    password: Rahi-8000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update